```javascript
// questions.js
// Format: { id, image?, question, options[] }

window.questions = [
  { id: 1, image: "", question: "A 45-year-old man presents to the emergency department with severe breathlessness and hypotension. On examination, his jugular venous pressure is raised, heart sounds are muffled, and systolic blood pressure falls by >10 mmHg during inspiration. Which of the following is the most likely diagnosis?", options: ["Cardiac tamponade", "Aortic regurgitation", "Complete heart block", "Patent ductus arteriosus"] },
  { id: 2, image: "", question: "A 68-year-old man presents with recurrent dizziness and fatigue. On examination, the physician notices intermittent giant pulsations in the neck veins. ECG shows complete atrioventricular dissociation. The prominent venous pulsations are due to atrial contraction against a closed tricuspid valve. Which of the following is the most likely jugular venous pulse finding?", options: ["Absent a wave", "Cannon a wave", "Large v wave", "Prominent y descent"] },
  { id: 3, image: "", question: "A 32-year-old pregnant woman in the third trimester is evaluated during a routine antenatal visit. She is asymptomatic. On auscultation, a low-pitched extra heart sound is heard just after S₂ during early diastole. The sound is best appreciated with the bell of the stethoscope at the apex in the left lateral position. Which of the following heart sounds is most likely heard?", options: ["S₄", "Opening snap", "S₃", "Ejection click"] },
  { id: 4, image: "", question: "A 72-year-old man presents with exertional breathlessness and occasional dizziness while walking uphill. On auscultation, a harsh murmur is heard at the right upper sternal border. The murmur begins after S₁, peaks in mid-systole, and decreases before S₂. Which of the following best describes this murmur?", options: ["Pansystolic murmur", "Early diastolic murmur", "Mid-diastolic murmur", "Ejection systolic murmur"] },
  { id: 5, image: "images/IMG_5327.jpeg", question: "A 12-year-old boy presents with fever and migratory polyarthritis 3 weeks after a sore throat. On examination, firm, painless, mobile nodules are seen over the extensor surface of the elbow. These nodules are classically associated with which of the following conditions?", options: ["Acute rheumatic fever", "Rheumatoid arthritis", "Systemic lupus erythematosus", "Infective endocarditis"] },
  { id: 6, image: "", question: "A 45-year-old man presents with exertional dyspnea and palpitations. On examination, he has a collapsing pulse and wide pulse pressure. While examining the oral cavity, the physician observes visible pulsation of the uvula with each cardiac cycle. Which of the following eponymous signs is most likely present?", options: ["Müller’s sign", "Corrigan’s sign", "Quincke’s sign", "de Musset’s sign"] },
  { id: 7, image: "", question: "A 38-year-old man presents with fever, fatigue, weight loss, and a new cardiac murmur. Blood culture grows a HACEK group organism. Echocardiography shows vegetation on the mitral valve. Which of the following is the most appropriate antibiotic therapy?", options: ["Vancomycin", "Ceftriaxone", "Doxycycline + Hydroxychloroquine", "Nafcillin + Gentamicin + Rifampicin"] },
  { id: 8, image: "", question: "A 24-year-old athlete presents with exertional syncope and palpitations. His father died suddenly at a young age. Echocardiography shows asymmetrical septal hypertrophy with obstruction near the left ventricular outflow tract. The condition is commonly associated with mutation of which of the following proteins?", options: ["Dystrophin", "Desmin", "β-myosin heavy chain", "Lamin A/C"] },
  { id: 9, image: "images/IMG_5328.jpeg", question: "A 62-year-old man presents with severe breathlessness, orthopnea, and paroxysmal nocturnal dyspnea. On examination, bilateral basal crepitations are present. Chest X-ray shows bilateral perihilar fluffy opacities giving a “bat wing” appearance. Which of the following is the most likely diagnosis?", options: ["Lobar pneumonia", "Pleural effusion", "Pneumothorax", "Cardiogenic pulmonary edema"] },
  { id: 10, image: "", question: "A 28-year-old man presents with sharp retrosternal chest pain following a recent viral illness. The pain radiates to the trapezius ridge, worsens on lying supine, and improves on leaning forward. On auscultation, a superficial scratching sound is heard near the left sternal border. ECG shows diffuse ST-segment elevation with PR-segment depression. Which of the following is the most likely diagnosis?", options: ["Acute pericarditis", "Acute myocardial infarction", "Pulmonary embolism", "Aortic dissection"] },
  { id: 11, image: "", question: "A 40-year-old man is brought to the emergency department after blunt chest trauma. He is severely dyspneic and hypotensive. On examination, his neck veins are distended and heart sounds are muffled. ECG shows electrical alternans. Echocardiography shows right ventricular diastolic collapse. Which of the following is the most likely diagnosis?", options: ["Acute pericarditis", "Cardiac tamponade", "Constrictive pericarditis", "Dilated cardiomyopathy"] },
  { id: 12, image: "", question: "A 52-year-old man with a past history of tuberculosis presents with progressive abdominal distension, pedal edema, and raised jugular venous pressure. He has no features of shock. On auscultation, an early diastolic sound is heard due to sudden limitation of ventricular filling. ECG shows low-voltage complexes, and imaging shows a calcified pericardium with loss of pericardial space. Which of the following is the most likely diagnosis?", options: ["Cardiac tamponade", "Acute pericarditis", "Constrictive pericarditis", "Restrictive cardiomyopathy"] },
  { id: 13, image: "", question: "A 46-year-old man presents with progressive fatigue, exertional dyspnea, and palpitations. He has a history of chronic alcohol intake. On examination, pulse shows pulsus alternans, and auscultation reveals S₃ gallop with a soft systolic murmur. Echocardiography shows dilatation of all 4 chambers with ejection fraction <40%. Which of the following is the most likely diagnosis?", options: ["Hypertrophic obstructive cardiomyopathy", "Restrictive cardiomyopathy", "Constrictive pericarditis", "Dilated cardiomyopathy"] },
  { id: 14, image: "", question: "A 55-year-old man presents with progressive pedal edema, abdominal distension, raised jugular venous pressure, and exertional dyspnea. ECG shows low-voltage complexes with AV blocks. Echocardiography shows biatrial enlargement, normal ventricular size, and ejection fraction of 60–70%. Which of the following is the most likely diagnosis?", options: ["Restrictive cardiomyopathy", "Dilated cardiomyopathy", "Hypertrophic obstructive cardiomyopathy", "Acute pericarditis"] },
  { id: 15, image: "", question: "A 21-year-old athlete collapses during a football match. He had a history of exertional dyspnea, angina, and syncopal episodes. On examination, a bisferiens pulse is felt. Auscultation reveals an ejection systolic murmur at the left sternal border, with no carotid radiation. Echocardiography shows a banana-shaped left ventricular cavity with ejection fraction >70%. Which of the following is the most likely diagnosis?", options: ["Dilated cardiomyopathy", "Hypertrophic obstructive cardiomyopathy", "Restrictive cardiomyopathy", "Constrictive pericarditis"] },
  { id: 16, image: "", question: "A 58-year-old man presents to the emergency department with sudden severe tearing chest pain radiating to the back. His blood pressure is 220/120 mmHg, and CT angiography confirms aortic dissection. The physician wants immediate blood pressure control. Which of the following is the most preferred initial drug?", options: ["Nicardipine", "Nitroglycerin", "Esmolol", "Sodium nitroprusside"] },
  { id: 17, image: "images/IMG_5329.jpeg", question: "A 56-year-old man presents to the emergency department with severe retrosternal chest pain radiating to the left arm. ECG shows ST-segment elevation in leads I and aVL. The infarct-related artery is suspected to be the left circumflex artery. Which of the following myocardial infarction locations is most likely?", options: ["Inferior wall myocardial infarction", "Anterior wall myocardial infarction", "Posterior wall myocardial infarction", "Lateral wall myocardial infarction"] },
  { id: 18, image: "images/IMG_5330.jpeg", question: "A 60-year-old man presents to the emergency department with severe retrosternal chest pain, sweating, and nausea. ECG shows ST-segment elevation in leads II, III, and aVF. The infarct-related artery is most likely the right coronary artery. Which of the following myocardial infarction locations is most likely?", options: ["Inferior wall myocardial infarction", "Lateral wall myocardial infarction", "Anterior wall myocardial infarction", "Posterior wall myocardial infarction"] },
  { id: 19, image: "images/IMG_5331.jpeg", question: "A 58-year-old man presents to the emergency department with crushing retrosternal chest pain, sweating, and breathlessness. ECG shows ST-segment elevation in V1–V4 and I, aVL, V₅, V₆. Coronary angiography reveals involvement of the left main coronary artery. Which of the following myocardial infarction locations is most likely?", options: ["Inferior wall myocardial infarction", "Anterolateral wall myocardial infarction", "Posterior wall myocardial infarction", "Right ventricular myocardial infarction"] },
  { id: 20, image: "images/IMG_5333.jpeg", question: "A 62-year-old man presents with intermittent palpitations and a feeling of “missed beats.” ECG shows one premature wide QRS complex occurring after every normal beat. These premature beats are not preceded by P waves and have similar QRS morphology throughout the tracing. Which of the following is the most likely rhythm abnormality?", options: ["Ventricular trigeminy", "Atrial bigeminy", "Ventricular bigeminy", "Ventricular couplets"] },
  { id: 21, image: "images/IMG_5334.jpeg", question: "A 70-year-old man with long-standing COPD is admitted to ICU with acute exacerbation. He develops palpitations and tachycardia. ECG shows narrow QRS complex tachycardia with more than three different P-wave morphologies and clear isoelectric intervals between P waves. Which of the following is the most likely diagnosis?", options: ["Atrial fibrillation", "Atrial flutter", "Ventricular bigeminy", "Multifocal atrial tachycardia"] },
  { id: 22, image: "images/IMG_5335.jpeg", question: "A 58-year-old man presents for routine evaluation before surgery. He is asymptomatic and has a regular pulse. ECG shows each P wave followed by a QRS complex, but the PR interval is prolonged and constant throughout the tracing. Which of the following is the most likely diagnosis?", options: ["First-degree AV block", "Mobitz type I second-degree AV block", "Mobitz type II second-degree AV block", "Complete heart block"] },
  { id: 23, image: "images/IMG_5336.jpeg", question: "A 64-year-old man presents with intermittent dizziness and fatigue. ECG shows progressive lengthening of the PR interval until one P wave is not followed by a QRS complex. After the dropped beat, the cycle repeats again. Which of the following is the most likely diagnosis?", options: ["First-degree AV block", "Mobitz type I second-degree AV block", "Mobitz type II second-degree AV block", "Complete heart block"] },
  { id: 24, image: "images/IMG_5337.jpeg", question: "A 66-year-old man presents with recurrent episodes of dizziness and near-syncope. ECG shows a constant PR interval in successive conducted beats, but after every few beats, a P wave is not followed by a QRS complex. Which of the following is the most likely diagnosis?", options: ["First-degree AV block", "Mobitz type I second-degree AV block", "Mobitz type II second-degree AV block", "Complete heart block"] },
  { id: 25, image: "images/IMG_5338.jpeg", question: "A 72-year-old man presents with recurrent syncope, dizziness, and marked fatigue. Pulse rate is 38/min. ECG shows P waves and QRS complexes occurring independently, with no fixed relationship between P waves and QRS complexes. Which of the following is the most likely diagnosis?", options: ["First-degree AV block", "Mobitz type I second-degree AV block", "Mobitz type II second-degree AV block", "Third-degree AV block"] },
  { id: 26, image: "images/IMG_5339.jpeg", question: "A 34-year-old woman with Crohn disease presents with recurrent diarrhea, palpitations, and dizziness. Serum magnesium is low. ECG shows polymorphic ventricular tachycardia with QRS complexes changing amplitude and appearing to twist around the baseline. Which of the following is the most likely diagnosis?", options: ["Torsades de pointes", "Ventricular bigeminy", "Multifocal atrial tachycardia", "Atrial flutter"] },
  { id: 27, image: "images/IMG_5340.jpeg", question: "A 62-year-old man presents to the emergency department with acute retrosternal chest pain, sweating, and breathlessness. ECG shows ST depression with tall R waves in leads V₁–V₄. Which of the following myocardial infarction locations is most likely?", options: ["Posterior wall myocardial infarction", "Inferior wall myocardial infarction", "Anterior wall myocardial infarction", "Lateral wall myocardial infarction"] },
  { id: 28, image: "images/IMG_5341.jpeg", question: "A 28-year-old woman presents to the emergency department with sudden onset palpitations and anxiety. Pulse rate is 180/min and regular. Blood pressure is stable. ECG shows regular narrow QRS complex tachycardia, no visible P waves, and pseudo R′ waves in lead V₁. Which of the following is the first-line drug for acute termination of this rhythm?", options: ["Verapamil", "Adenosine", "Amiodarone", "Digoxin"] },
  { id: 29, image: "images/IMG_5342.jpeg", question: "A 24-year-old man presents with recurrent episodes of sudden-onset palpitations. ECG shows short PR interval, wide QRS complex, and slurred upstroke of QRS complex. He is diagnosed with Wolff-Parkinson-White syndrome. Which of the following is the best long-term management?", options: ["Adenosine", "Verapamil", "Catheter ablation", "Digoxin"] },
  { id: 30, image: "images/IMG_5343.jpeg", question: "A 68-year-old man with long-standing hypertension presents with sudden onset palpitations and mild breathlessness. Pulse is irregularly irregular. ECG shows narrow QRS complexes, irregular RR intervals, and absence of distinct P waves. Which of the following is the most likely diagnosis?", options: ["Atrial flutter", "Multifocal atrial tachycardia", "Paroxysmal supraventricular tachycardia", "Atrial fibrillation"] }

  // Continue questions 31–180 in same format after removing answerIndex and correctAnswerText
];
```
